kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: px-check-pvc
spec:
    storageClassName: px-csi-db
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
            
